# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'votr_dbt'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'votr_dbt'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  votr_dbt:
    staging:
      +schema: staging  # Set the schema for the staging directory
      +materialized: table
      stg_congress_member_contact_info:
        +materialized: table
      stg_congress_member_ids:
        +materialized: table
      stg_congress_member_leadership:
        +materialized: table
      stg_congress_member_social_media:
        +materialized: table
      stg_congress_member:
        +materialized: table
      stg_congress_member_terms:
        +materialized: table
    congress:  # Set the schema for the congress directory
      dimensions:
        tables:
          +materialized: table
          dim_congress_member_contact_info_historical:
            +materialized: table
          dim_congress_member_historical:
            +materialized: table
          dim_congress_member_ids_historical:
            +materialized: table
          dim_congress_member_leadership_historical:
            +materialized: table
          dim_congress_member_social_media_historical:
            +materialized: table
          dim_congress_member_terms_historical:
            +materialized: table
        views:
          +materialized: view
          dim_congress_member_contact_info:
            +materialized: view
          dim_congress_member_ids:
            +materialized: view
          dim_congress_member_leadership:
            +materialized: view
          dim_congress_member_social_media:
            +materialized: view
          dim_congress_member:
            +materialized: view
    bills:
      +schema: public
      +materialized: table
    votes:
      +schema: public
      +materialized: table

# models:
#   votr_dbt:
#     staging:
#       +schema: staging  # Set the schema for the staging directory
#       +materialized: table
#       stg_congress_member_contact_info:
#         +materialized: table
#       stg_congress_member_ids:
#         +materialized: table
#       stg_congress_member_leadership:
#         +materialized: table
#       stg_congress_member_social_media:
#         +materialized: table
#       stg_congress_member:
#         +materialized: table
#     congress:
#       +materialized: table
#       dimensions:
#         +materialized: table
#         dim_congress_member_ids_historical:
#           +materialized: table
#         dim_congress_member_ids:
#           +materialized: table
#         dim_congress_member_leadership_historical:
#           +materialized: table
#         dim_congress_member_leadership:
#           +materialized: table
#         dim_member_contact_info_historical:
#           +materialized: table
#         dim_member_historical:
#           +materialized: table
#         dim_member_social_media_historical:
#           +materialized: table
#         dim_member_social_media:
#           +materialized: table
#         dim_member:
#           +materialized: view
#         dim_member_contact_info:
#           +materialized: view
#         dim_congress_member_ids:
#           +materialized: view
#         dim_member_social_media:
#           +materialized: view
#     bills:
#       +materialized: table
#     votes:
#       +materialized: table
      