{{ config(
    materialized='table',
    primary_key = 'id'
) }}

WITH cd_income AS (
    SELECT
        year,
        congressional_district,
        state_fip,
        'us' AS country,
        CAST(hh_income_total AS BIGNUMERIC) AS cd_hh_income_total,
        CAST(hh_income_total AS BIGNUMERIC) / CAST(hh_income_total AS BIGNUMERIC) AS cd_pct_hh_income_total,
        CAST(hh_income_less_10k AS BIGNUMERIC) AS cd_hh_income_less_10k,
        CAST(hh_income_less_10k AS BIGNUMERIC) / CAST(hh_income_total AS BIGNUMERIC) AS cd_pct_hh_income_less_10k,
        CAST(hh_income_10k_to_14k AS BIGNUMERIC) AS cd_hh_income_10k_to_14k,
        CAST(hh_income_10k_to_14k AS BIGNUMERIC) / CAST(hh_income_total AS BIGNUMERIC) AS cd_pct_hh_income_10k_to_14k,
        CAST(hh_income_15k_to_19k AS BIGNUMERIC) AS cd_hh_income_15k_to_19k,
        CAST(hh_income_15k_to_19k AS BIGNUMERIC) / CAST(hh_income_total AS BIGNUMERIC) AS cd_pct_hh_income_15k_to_19k,
        CAST(hh_income_20k_to_24k AS BIGNUMERIC) AS cd_hh_income_20k_to_24k,
        CAST(hh_income_20k_to_24k AS BIGNUMERIC) / CAST(hh_income_total AS BIGNUMERIC) AS cd_pct_hh_income_20k_to_24k,
        CAST(hh_income_25k_to_29k AS BIGNUMERIC) AS cd_hh_income_25k_to_29k,
        CAST(hh_income_25k_to_29k AS BIGNUMERIC) / CAST(hh_income_total AS BIGNUMERIC) AS cd_pct_hh_income_25k_to_29k,
        CAST(hh_income_30k_to_34k AS BIGNUMERIC) AS cd_hh_income_30k_to_34k,
        CAST(hh_income_30k_to_34k AS BIGNUMERIC) / CAST(hh_income_total AS BIGNUMERIC) AS cd_pct_hh_income_30k_to_34k,
        CAST(hh_income_35k_to_39k AS BIGNUMERIC) AS cd_hh_income_35k_to_39k,
        CAST(hh_income_35k_to_39k AS BIGNUMERIC) / CAST(hh_income_total AS BIGNUMERIC) AS cd_pct_hh_income_35k_to_39k,
        CAST(hh_income_40k_to_44k AS BIGNUMERIC) AS cd_hh_income_40k_to_44k,
        CAST(hh_income_40k_to_44k AS BIGNUMERIC) / CAST(hh_income_total AS BIGNUMERIC) AS cd_pct_hh_income_40k_to_44k,
        CAST(hh_income_45k_to_49k AS BIGNUMERIC) AS cd_hh_income_45k_to_49k,
        CAST(hh_income_45k_to_49k AS BIGNUMERIC) / CAST(hh_income_total AS BIGNUMERIC) AS cd_pct_hh_income_45k_to_49k,
        CAST(hh_income_50k_to_59k AS BIGNUMERIC) AS cd_hh_income_50k_to_59k,
        CAST(hh_income_50k_to_59k AS BIGNUMERIC) / CAST(hh_income_total AS BIGNUMERIC) AS cd_pct_hh_income_50k_to_59k,
        CAST(hh_income_60k_to_74k AS BIGNUMERIC) AS cd_hh_income_60k_to_74k,
        CAST(hh_income_60k_to_74k AS BIGNUMERIC) / CAST(hh_income_total AS BIGNUMERIC) AS cd_pct_hh_income_60k_to_74k,
        CAST(hh_income_75k_to_99k AS BIGNUMERIC) AS cd_hh_income_75k_to_99k,
        CAST(hh_income_75k_to_99k AS BIGNUMERIC) / CAST(hh_income_total AS BIGNUMERIC) AS cd_pct_hh_income_75k_to_99k,
        CAST(hh_income_100k_to_124k AS BIGNUMERIC) AS cd_hh_income_100k_to_124k,
        CAST(hh_income_100k_to_124k AS BIGNUMERIC) / CAST(hh_income_total AS BIGNUMERIC) AS cd_pct_hh_income_100k_to_124k,
        CAST(hh_income_125k_to_149k AS BIGNUMERIC) AS cd_hh_income_125k_to_149k,
        CAST(hh_income_125k_to_149k AS BIGNUMERIC) / CAST(hh_income_total AS BIGNUMERIC) AS cd_pct_hh_income_125k_to_149k,
        CAST(hh_income_150k_to_199k AS BIGNUMERIC) AS cd_hh_income_150k_to_199k,
        CAST(hh_income_150k_to_199k AS BIGNUMERIC) / CAST(hh_income_total AS BIGNUMERIC) AS cd_pct_hh_income_150k_to_199k,
        CAST(hh_income_200k_or_more AS BIGNUMERIC) AS cd_hh_income_200k_or_more,
        CAST(hh_income_200k_or_more AS BIGNUMERIC) / CAST(hh_income_total AS BIGNUMERIC) AS cd_pct_hh_income_200k_or_more,
        CAST(median_family_income AS BIGNUMERIC) AS cd_median_family_income
    FROM
        {{ ref('acs5_cd_income_historical') }}
    WHERE congressional_district NOT LIKE 'ZZ'
),

state_income AS (
    SELECT
        year,
        state_fip,
        'us' AS country,
        CAST(hh_income_total AS BIGNUMERIC) AS state_hh_income_total,
        CAST(hh_income_total AS BIGNUMERIC) / CAST(hh_income_total AS BIGNUMERIC) AS state_pct_hh_income_total,
        CAST(hh_income_less_10k AS BIGNUMERIC) AS state_hh_income_less_10k,
        CAST(hh_income_less_10k AS BIGNUMERIC) / CAST(hh_income_total AS BIGNUMERIC) AS state_pct_hh_income_less_10k,
        CAST(hh_income_10k_to_14k AS BIGNUMERIC) AS state_hh_income_10k_to_14k,
        CAST(hh_income_10k_to_14k AS BIGNUMERIC) / CAST(hh_income_total AS BIGNUMERIC) AS state_pct_hh_income_10k_to_14k,
        CAST(hh_income_15k_to_19k AS BIGNUMERIC) AS state_hh_income_15k_to_19k,
        CAST(hh_income_15k_to_19k AS BIGNUMERIC) / CAST(hh_income_total AS BIGNUMERIC) AS state_pct_hh_income_15k_to_19k,
        CAST(hh_income_20k_to_24k AS BIGNUMERIC) AS state_hh_income_20k_to_24k,
        CAST(hh_income_20k_to_24k AS BIGNUMERIC) / CAST(hh_income_total AS BIGNUMERIC) AS state_pct_hh_income_20k_to_24k,
        CAST(hh_income_25k_to_29k AS BIGNUMERIC) AS state_hh_income_25k_to_29k,
        CAST(hh_income_25k_to_29k AS BIGNUMERIC) / CAST(hh_income_total AS BIGNUMERIC) AS state_pct_hh_income_25k_to_29k,
        CAST(hh_income_30k_to_34k AS BIGNUMERIC) AS state_hh_income_30k_to_34k,
        CAST(hh_income_30k_to_34k AS BIGNUMERIC) / CAST(hh_income_total AS BIGNUMERIC) AS state_pct_hh_income_30k_to_34k,
        CAST(hh_income_35k_to_39k AS BIGNUMERIC) AS state_hh_income_35k_to_39k,
        CAST(hh_income_35k_to_39k AS BIGNUMERIC) / CAST(hh_income_total AS BIGNUMERIC) AS state_pct_hh_income_35k_to_39k,
        CAST(hh_income_40k_to_44k AS BIGNUMERIC) AS state_hh_income_40k_to_44k,
        CAST(hh_income_40k_to_44k AS BIGNUMERIC) / CAST(hh_income_total AS BIGNUMERIC) AS state_pct_hh_income_40k_to_44k,
        CAST(hh_income_45k_to_49k AS BIGNUMERIC) AS state_hh_income_45k_to_49k,
        CAST(hh_income_45k_to_49k AS BIGNUMERIC) / CAST(hh_income_total AS BIGNUMERIC) AS state_pct_hh_income_45k_to_49k,
        CAST(hh_income_50k_to_59k AS BIGNUMERIC) AS state_hh_income_50k_to_59k,
        CAST(hh_income_50k_to_59k AS BIGNUMERIC) / CAST(hh_income_total AS BIGNUMERIC) AS state_pct_hh_income_50k_to_59k,
        CAST(hh_income_60k_to_74k AS BIGNUMERIC) AS state_hh_income_60k_to_74k,
        CAST(hh_income_60k_to_74k AS BIGNUMERIC) / CAST(hh_income_total AS BIGNUMERIC) AS state_pct_hh_income_60k_to_74k,
        CAST(hh_income_75k_to_99k AS BIGNUMERIC) AS state_hh_income_75k_to_99k,
        CAST(hh_income_75k_to_99k AS BIGNUMERIC) / CAST(hh_income_total AS BIGNUMERIC) AS state_pct_hh_income_75k_to_99k,
        CAST(hh_income_100k_to_124k AS BIGNUMERIC) AS state_hh_income_100k_to_124k,
        CAST(hh_income_100k_to_124k AS BIGNUMERIC) / CAST(hh_income_total AS BIGNUMERIC) AS state_pct_hh_income_100k_to_124k,
        CAST(hh_income_125k_to_149k AS BIGNUMERIC) AS state_hh_income_125k_to_149k,
        CAST(hh_income_125k_to_149k AS BIGNUMERIC) / CAST(hh_income_total AS BIGNUMERIC) AS state_pct_hh_income_125k_to_149k,
        CAST(hh_income_150k_to_199k AS BIGNUMERIC) AS state_hh_income_150k_to_199k,
        CAST(hh_income_150k_to_199k AS BIGNUMERIC) / CAST(hh_income_total AS BIGNUMERIC) AS state_pct_hh_income_150k_to_199k,
        CAST(hh_income_200k_or_more AS BIGNUMERIC) AS state_hh_income_200k_or_more,
        CAST(hh_income_200k_or_more AS BIGNUMERIC) / CAST(hh_income_total AS BIGNUMERIC) AS state_pct_hh_income_200k_or_more,
        CAST(median_family_income AS BIGNUMERIC) AS state_median_family_income
    FROM
        {{ ref('acs5_state_income_historical') }}
),

us_income AS (
    SELECT
        year,
        'us' AS country,
        CAST(hh_income_total AS BIGNUMERIC) AS us_hh_income_total,
        CAST(hh_income_total AS BIGNUMERIC) / CAST(hh_income_total AS BIGNUMERIC) AS us_pct_hh_income_total,
        CAST(hh_income_less_10k AS BIGNUMERIC) AS us_hh_income_less_10k,
        CAST(hh_income_less_10k AS BIGNUMERIC) / CAST(hh_income_total AS BIGNUMERIC) AS us_pct_hh_income_less_10k,
        CAST(hh_income_10k_to_14k AS BIGNUMERIC) AS us_hh_income_10k_to_14k,
        CAST(hh_income_10k_to_14k AS BIGNUMERIC) / CAST(hh_income_total AS BIGNUMERIC) AS us_pct_hh_income_10k_to_14k,
        CAST(hh_income_15k_to_19k AS BIGNUMERIC) AS us_hh_income_15k_to_19k,
        CAST(hh_income_15k_to_19k AS BIGNUMERIC) / CAST(hh_income_total AS BIGNUMERIC) AS us_pct_hh_income_15k_to_19k,
        CAST(hh_income_20k_to_24k AS BIGNUMERIC) AS us_hh_income_20k_to_24k,
        CAST(hh_income_20k_to_24k AS BIGNUMERIC) / CAST(hh_income_total AS BIGNUMERIC) AS us_pct_hh_income_20k_to_24k,
        CAST(hh_income_25k_to_29k AS BIGNUMERIC) AS us_hh_income_25k_to_29k,
        CAST(hh_income_25k_to_29k AS BIGNUMERIC) / CAST(hh_income_total AS BIGNUMERIC) AS us_pct_hh_income_25k_to_29k,
        CAST(hh_income_30k_to_34k AS BIGNUMERIC) AS us_hh_income_30k_to_34k,
        CAST(hh_income_30k_to_34k AS BIGNUMERIC) / CAST(hh_income_total AS BIGNUMERIC) AS us_pct_hh_income_30k_to_34k,
        CAST(hh_income_35k_to_39k AS BIGNUMERIC) AS us_hh_income_35k_to_39k,
        CAST(hh_income_35k_to_39k AS BIGNUMERIC) / CAST(hh_income_total AS BIGNUMERIC) AS us_pct_hh_income_35k_to_39k,
        CAST(hh_income_40k_to_44k AS BIGNUMERIC) AS us_hh_income_40k_to_44k,
        CAST(hh_income_40k_to_44k AS BIGNUMERIC) / CAST(hh_income_total AS BIGNUMERIC) AS us_pct_hh_income_40k_to_44k,
        CAST(hh_income_45k_to_49k AS BIGNUMERIC) AS us_hh_income_45k_to_49k,
        CAST(hh_income_45k_to_49k AS BIGNUMERIC) / CAST(hh_income_total AS BIGNUMERIC) AS us_pct_hh_income_45k_to_49k,
        CAST(hh_income_50k_to_59k AS BIGNUMERIC) AS us_hh_income_50k_to_59k,
        CAST(hh_income_50k_to_59k AS BIGNUMERIC) / CAST(hh_income_total AS BIGNUMERIC) AS us_pct_hh_income_50k_to_59k,
        CAST(hh_income_60k_to_74k AS BIGNUMERIC) AS us_hh_income_60k_to_74k,
        CAST(hh_income_60k_to_74k AS BIGNUMERIC) / CAST(hh_income_total AS BIGNUMERIC) AS us_pct_hh_income_60k_to_74k,
        CAST(hh_income_75k_to_99k AS BIGNUMERIC) AS us_hh_income_75k_to_99k,
        CAST(hh_income_75k_to_99k AS BIGNUMERIC) / CAST(hh_income_total AS BIGNUMERIC) AS us_pct_hh_income_75k_to_99k,
        CAST(hh_income_100k_to_124k AS BIGNUMERIC) AS us_hh_income_100k_to_124k,
        CAST(hh_income_100k_to_124k AS BIGNUMERIC) / CAST(hh_income_total AS BIGNUMERIC) AS us_pct_hh_income_100k_to_124k,
        CAST(hh_income_125k_to_149k AS BIGNUMERIC) AS us_hh_income_125k_to_149k,
        CAST(hh_income_125k_to_149k AS BIGNUMERIC) / CAST(hh_income_total AS BIGNUMERIC) AS us_pct_hh_income_125k_to_149k,
        CAST(hh_income_150k_to_199k AS BIGNUMERIC) AS us_hh_income_150k_to_199k,
        CAST(hh_income_150k_to_199k AS BIGNUMERIC) / CAST(hh_income_total AS BIGNUMERIC) AS us_pct_hh_income_150k_to_199k,
        CAST(hh_income_200k_or_more AS BIGNUMERIC) AS us_hh_income_200k_or_more,
        CAST(hh_income_200k_or_more AS BIGNUMERIC) / CAST(hh_income_total AS BIGNUMERIC) AS us_pct_hh_income_200k_or_more,
        CAST(median_family_income AS BIGNUMERIC) AS us_median_family_income
    FROM
        {{ ref('acs5_us_income_historical') }}
)

SELECT
    {{ dbt_utils.generate_surrogate_key(['cd_income.year', 'cd_income.state_fip', 'cd_income.congressional_district']) }} AS id,
    cd_income.year,
    cd_income.congressional_district,
    cd_income.state_fip,
    cd_income.country AS cd_country,
    cd_income.cd_hh_income_total,
    cd_income.cd_pct_hh_income_total,
    cd_income.cd_hh_income_less_10k,
    cd_income.cd_pct_hh_income_less_10k,
    cd_income.cd_hh_income_10k_to_14k,
    cd_income.cd_pct_hh_income_10k_to_14k,
    cd_income.cd_hh_income_15k_to_19k,
    cd_income.cd_pct_hh_income_15k_to_19k,
    cd_income.cd_hh_income_20k_to_24k,
    cd_income.cd_pct_hh_income_20k_to_24k,
    cd_income.cd_hh_income_25k_to_29k,
    cd_income.cd_pct_hh_income_25k_to_29k,
    cd_income.cd_hh_income_30k_to_34k,
    cd_income.cd_pct_hh_income_30k_to_34k,
    cd_income.cd_hh_income_35k_to_39k,
    cd_income.cd_pct_hh_income_35k_to_39k,
    cd_income.cd_hh_income_40k_to_44k,
    cd_income.cd_pct_hh_income_40k_to_44k,
    cd_income.cd_hh_income_45k_to_49k,
    cd_income.cd_pct_hh_income_45k_to_49k,
    cd_income.cd_hh_income_50k_to_59k,
    cd_income.cd_pct_hh_income_50k_to_59k,
    cd_income.cd_hh_income_60k_to_74k,
    cd_income.cd_pct_hh_income_60k_to_74k,
    cd_income.cd_hh_income_75k_to_99k,
    cd_income.cd_pct_hh_income_75k_to_99k,
    cd_income.cd_hh_income_100k_to_124k,
    cd_income.cd_pct_hh_income_100k_to_124k,
    cd_income.cd_hh_income_125k_to_149k,
    cd_income.cd_pct_hh_income_125k_to_149k,
    cd_income.cd_hh_income_150k_to_199k,
    cd_income.cd_pct_hh_income_150k_to_199k,
    cd_income.cd_hh_income_200k_or_more,
    cd_income.cd_pct_hh_income_200k_or_more,
    cd_income.cd_median_family_income,
    state_income.state_hh_income_total,
    state_income.state_pct_hh_income_total,
    state_income.state_hh_income_less_10k,
    state_income.state_pct_hh_income_less_10k,
    state_income.state_hh_income_10k_to_14k,
    state_income.state_pct_hh_income_10k_to_14k,
    state_income.state_hh_income_15k_to_19k,
    state_income.state_pct_hh_income_15k_to_19k,
    state_income.state_hh_income_20k_to_24k,
    state_income.state_pct_hh_income_20k_to_24k,    
    state_income.state_hh_income_25k_to_29k,
    state_income.state_pct_hh_income_25k_to_29k,
    state_income.state_hh_income_30k_to_34k,
    state_income.state_pct_hh_income_30k_to_34k,
    state_income.state_hh_income_35k_to_39k,
    state_income.state_pct_hh_income_35k_to_39k,
    state_income.state_hh_income_40k_to_44k,
    state_income.state_pct_hh_income_40k_to_44k,
    state_income.state_hh_income_45k_to_49k,
    state_income.state_pct_hh_income_45k_to_49k,
    state_income.state_hh_income_50k_to_59k,
    state_income.state_pct_hh_income_50k_to_59k,
    state_income.state_hh_income_60k_to_74k,
    state_income.state_pct_hh_income_60k_to_74k,
    state_income.state_hh_income_75k_to_99k,
    state_income.state_pct_hh_income_75k_to_99k,
    state_income.state_hh_income_100k_to_124k,
    state_income.state_pct_hh_income_100k_to_124k,
    state_income.state_hh_income_125k_to_149k,
    state_income.state_pct_hh_income_125k_to_149k,
    state_income.state_hh_income_150k_to_199k,
    state_income.state_pct_hh_income_150k_to_199k,
    state_income.state_hh_income_200k_or_more,
    state_income.state_pct_hh_income_200k_or_more,
    state_income.state_median_family_income,
    us_income.us_hh_income_total,
    us_income.us_pct_hh_income_total,
    us_income.us_hh_income_less_10k,
    us_income.us_pct_hh_income_less_10k,
    us_income.us_hh_income_10k_to_14k,
    us_income.us_pct_hh_income_10k_to_14k,
    us_income.us_hh_income_15k_to_19k,
    us_income.us_pct_hh_income_15k_to_19k,
    us_income.us_hh_income_20k_to_24k,
    us_income.us_pct_hh_income_20k_to_24k,
    us_income.us_hh_income_25k_to_29k,
    us_income.us_pct_hh_income_25k_to_29k,
    us_income.us_hh_income_30k_to_34k,
    us_income.us_pct_hh_income_30k_to_34k,
    us_income.us_hh_income_35k_to_39k,
    us_income.us_pct_hh_income_35k_to_39k,
    us_income.us_hh_income_40k_to_44k,
    us_income.us_pct_hh_income_40k_to_44k,
    us_income.us_hh_income_45k_to_49k,
    us_income.us_pct_hh_income_45k_to_49k,
    us_income.us_hh_income_50k_to_59k,
    us_income.us_pct_hh_income_50k_to_59k,
    us_income.us_hh_income_60k_to_74k,
    us_income.us_pct_hh_income_60k_to_74k,
    us_income.us_hh_income_75k_to_99k,
    us_income.us_pct_hh_income_75k_to_99k,
    us_income.us_hh_income_100k_to_124k,
    us_income.us_pct_hh_income_100k_to_124k,
    us_income.us_hh_income_125k_to_149k,
    us_income.us_pct_hh_income_125k_to_149k,
    us_income.us_hh_income_150k_to_199k,
    us_income.us_pct_hh_income_150k_to_199k,
    us_income.us_hh_income_200k_or_more,
    us_income.us_pct_hh_income_200k_or_more,
    us_income.us_median_family_income
FROM
    cd_income
LEFT JOIN
    state_income ON cd_income.state_fip = state_income.state_fip
        AND cd_income.year = state_income.year
LEFT JOIN
    us_income ON cd_income.country = us_income.country
        AND cd_income.year = us_income.year
-- Removed ORDER BY clause