{{ config(
    materialized='table',
    primary_key = 'id'
) }}


with cd_income as (
    select
        year,
        congressional_district,
        state_fip,
        'us' as country,
        hh_income_total::float as cd_hh_income_total,
        hh_income_total::float / hh_income_total::float as cd_pct_hh_income_total,
        hh_income_less_10k::float as cd_hh_income_less_10k,
        hh_income_less_10k::float / hh_income_total::float as cd_pct_hh_income_less_10k,
        hh_income_10k_to_14k::float as cd_hh_income_10k_to_14k,
        hh_income_10k_to_14k::float / hh_income_total::float as cd_pct_hh_income_10k_to_14k,
        hh_income_15k_to_19k::float as cd_hh_income_15k_to_19k,
        hh_income_15k_to_19k::float / hh_income_total::float as cd_pct_hh_income_15k_to_19k,
        hh_income_20k_to_24k::float as cd_hh_income_20k_to_24k,
        hh_income_20k_to_24k::float / hh_income_total::float as cd_pct_hh_income_20k_to_24k,
        hh_income_25k_to_29k::float as cd_hh_income_25k_to_29k,
        hh_income_25k_to_29k::float / hh_income_total::float as cd_pct_hh_income_25k_to_29k,
        hh_income_30k_to_34k::float as cd_hh_income_30k_to_34k,
        hh_income_30k_to_34k::float / hh_income_total::float as cd_pct_hh_income_30k_to_34k,
        hh_income_35k_to_39k::float as cd_hh_income_35k_to_39k,
        hh_income_35k_to_39k::float / hh_income_total::float as cd_pct_hh_income_35k_to_39k,
        hh_income_40k_to_44k::float as cd_hh_income_40k_to_44k,
        hh_income_40k_to_44k::float / hh_income_total::float as cd_pct_hh_income_40k_to_44k,
        hh_income_45k_to_49k::float as cd_hh_income_45k_to_49k,
        hh_income_45k_to_49k::float / hh_income_total::float as cd_pct_hh_income_45k_to_49k,
        hh_income_50k_to_59k::float as cd_hh_income_50k_to_59k,
        hh_income_50k_to_59k::float / hh_income_total::float as cd_pct_hh_income_50k_to_59k,
        hh_income_60k_to_74k::float as cd_hh_income_60k_to_74k,
        hh_income_60k_to_74k::float / hh_income_total::float as cd_pct_hh_income_60k_to_74k,
        hh_income_75k_to_99k::float as cd_hh_income_75k_to_99k,
        hh_income_75k_to_99k::float / hh_income_total::float as cd_pct_hh_income_75k_to_99k,
        hh_income_100k_to_124k::float as cd_hh_income_100k_to_124k,
        hh_income_100k_to_124k::float / hh_income_total::float as cd_pct_hh_income_100k_to_124k,
        hh_income_125k_to_149k::float as cd_hh_income_125k_to_149k,
        hh_income_125k_to_149k::float / hh_income_total::float as cd_pct_hh_income_125k_to_149k,
        hh_income_150k_to_199k::float as cd_hh_income_150k_to_199k,
        hh_income_150k_to_199k::float / hh_income_total::float as cd_pct_hh_income_150k_to_199k,
        hh_income_200k_or_more::float as cd_hh_income_200k_or_more,
        hh_income_200k_or_more::float / hh_income_total::float as cd_pct_hh_income_200k_or_more,
        median_family_income::float as cd_median_family_income
    from {{ref('acs5_cd_income_historical')}}
    where congressional_district not like 'ZZ'
    order by state_fip, congressional_district, year
),

state_income as (
    select
        year,
        state_fip,
        'us' as country,
        hh_income_total::float as state_hh_income_total,
        hh_income_total::float / hh_income_total::float as state_pct_hh_income_total,
        hh_income_less_10k::float as state_hh_income_less_10k,
        hh_income_less_10k::float / hh_income_total::float as state_pct_hh_income_less_10k,
        hh_income_10k_to_14k::float as state_hh_income_10k_to_14k,
        hh_income_10k_to_14k::float / hh_income_total::float as state_pct_hh_income_10k_to_14k,
        hh_income_15k_to_19k::float as state_hh_income_15k_to_19k,
        hh_income_15k_to_19k::float / hh_income_total::float as state_pct_hh_income_15k_to_19k,
        hh_income_20k_to_24k::float as state_hh_income_20k_to_24k,
        hh_income_20k_to_24k::float / hh_income_total::float as state_pct_hh_income_20k_to_24k,
        hh_income_25k_to_29k::float as state_hh_income_25k_to_29k,
        hh_income_25k_to_29k::float / hh_income_total::float as state_pct_hh_income_25k_to_29k,
        hh_income_30k_to_34k::float as state_hh_income_30k_to_34k,
        hh_income_30k_to_34k::float / hh_income_total::float as state_pct_hh_income_30k_to_34k,
        hh_income_35k_to_39k::float as state_hh_income_35k_to_39k,
        hh_income_35k_to_39k::float / hh_income_total::float as state_pct_hh_income_35k_to_39k,
        hh_income_40k_to_44k::float as state_hh_income_40k_to_44k,
        hh_income_40k_to_44k::float / hh_income_total::float as state_pct_hh_income_40k_to_44k,
        hh_income_45k_to_49k::float as state_hh_income_45k_to_49k,
        hh_income_45k_to_49k::float / hh_income_total::float as state_pct_hh_income_45k_to_49k,
        hh_income_50k_to_59k::float as state_hh_income_50k_to_59k,
        hh_income_50k_to_59k::float / hh_income_total::float as state_pct_hh_income_50k_to_59k,
        hh_income_60k_to_74k::float as state_hh_income_60k_to_74k,
        hh_income_60k_to_74k::float / hh_income_total::float as state_pct_hh_income_60k_to_74k,
        hh_income_75k_to_99k::float as state_hh_income_75k_to_99k,
        hh_income_75k_to_99k::float / hh_income_total::float as state_pct_hh_income_75k_to_99k,
        hh_income_100k_to_124k::float as state_hh_income_100k_to_124k,
        hh_income_100k_to_124k::float / hh_income_total::float as state_pct_hh_income_100k_to_124k,
        hh_income_125k_to_149k::float as state_hh_income_125k_to_149k,
        hh_income_125k_to_149k::float / hh_income_total::float as state_pct_hh_income_125k_to_149k,
        hh_income_150k_to_199k::float as state_hh_income_150k_to_199k,
        hh_income_150k_to_199k::float / hh_income_total::float as state_pct_hh_income_150k_to_199k,
        hh_income_200k_or_more::float as state_hh_income_200k_or_more,
        hh_income_200k_or_more::float / hh_income_total::float as state_pct_hh_income_200k_or_more,
        median_family_income::float as state_median_family_income
    from {{ref('acs5_state_income_historical')}}
    order by state_fip, year
),

us_income as (
    select
        year,
        'us' as country,
        hh_income_total::float as us_hh_income_total,
        hh_income_total::float / hh_income_total::float as us_pct_hh_income_total,
        hh_income_less_10k::float as us_hh_income_less_10k,
        hh_income_less_10k::float / hh_income_total::float as us_pct_hh_income_less_10k,
        hh_income_10k_to_14k::float as us_hh_income_10k_to_14k,
        hh_income_10k_to_14k::float / hh_income_total::float as us_pct_hh_income_10k_to_14k,
        hh_income_15k_to_19k::float as us_hh_income_15k_to_19k,
        hh_income_15k_to_19k::float / hh_income_total::float as us_pct_hh_income_15k_to_19k,
        hh_income_20k_to_24k::float as us_hh_income_20k_to_24k,
        hh_income_20k_to_24k::float / hh_income_total::float as us_pct_hh_income_20k_to_24k,
        hh_income_25k_to_29k::float as us_hh_income_25k_to_29k,
        hh_income_25k_to_29k::float / hh_income_total::float as us_pct_hh_income_25k_to_29k,
        hh_income_30k_to_34k::float as us_hh_income_30k_to_34k,
        hh_income_30k_to_34k::float / hh_income_total::float as us_pct_hh_income_30k_to_34k,
        hh_income_35k_to_39k::float as us_hh_income_35k_to_39k,
        hh_income_35k_to_39k::float / hh_income_total::float as us_pct_hh_income_35k_to_39k,
        hh_income_40k_to_44k::float as us_hh_income_40k_to_44k,
        hh_income_40k_to_44k::float / hh_income_total::float as us_pct_hh_income_40k_to_44k,
        hh_income_45k_to_49k::float as us_hh_income_45k_to_49k,
        hh_income_45k_to_49k::float / hh_income_total::float as us_pct_hh_income_45k_to_49k,
        hh_income_50k_to_59k::float as us_hh_income_50k_to_59k,
        hh_income_50k_to_59k::float / hh_income_total::float as us_pct_hh_income_50k_to_59k,
        hh_income_60k_to_74k::float as us_hh_income_60k_to_74k,
        hh_income_60k_to_74k::float / hh_income_total::float as us_pct_hh_income_60k_to_74k,
        hh_income_75k_to_99k::float as us_hh_income_75k_to_99k,
        hh_income_75k_to_99k::float / hh_income_total::float as us_pct_hh_income_75k_to_99k,
        hh_income_100k_to_124k::float as us_hh_income_100k_to_124k,
        hh_income_100k_to_124k::float / hh_income_total::float as us_pct_hh_income_100k_to_124k,
        hh_income_125k_to_149k::float as us_hh_income_125k_to_149k,
        hh_income_125k_to_149k::float / hh_income_total::float as us_pct_hh_income_125k_to_149k,
        hh_income_150k_to_199k::float as us_hh_income_150k_to_199k,
        hh_income_150k_to_199k::float / hh_income_total::float as us_pct_hh_income_150k_to_199k,
        hh_income_200k_or_more::float as us_hh_income_200k_or_more,
        hh_income_200k_or_more::float / hh_income_total::float as us_pct_hh_income_200k_or_more,
        median_family_income::float as us_median_family_income
    from {{ref( 'acs5_us_income_historical')}}
    order by year
)

select
    {{dbt_utils.generate_surrogate_key(['cd_income.year', 'cd_income.state_fip', 'cd_income.congressional_district'])}} as id,
    cd_income.year,
    cd_income.congressional_district,
    cd_income.state_fip,
    cd_income.country as cd_country,
    cd_income.cd_hh_income_total,
    cd_income.cd_pct_hh_income_total,
    cd_income.cd_hh_income_less_10k,
    cd_income.cd_pct_hh_income_less_10k,
    cd_income.cd_hh_income_10k_to_14k,
    cd_income.cd_pct_hh_income_10k_to_14k,
    cd_income.cd_hh_income_15k_to_19k,
    cd_income.cd_pct_hh_income_15k_to_19k,
    cd_income.cd_hh_income_20k_to_24k,
    cd_income.cd_pct_hh_income_20k_to_24k,
    cd_income.cd_hh_income_25k_to_29k,
    cd_income.cd_pct_hh_income_25k_to_29k,
    cd_income.cd_hh_income_30k_to_34k,
    cd_income.cd_pct_hh_income_30k_to_34k,
    cd_income.cd_hh_income_35k_to_39k,
    cd_income.cd_pct_hh_income_35k_to_39k,
    cd_income.cd_hh_income_40k_to_44k,
    cd_income.cd_pct_hh_income_40k_to_44k,
    cd_income.cd_hh_income_45k_to_49k,
    cd_income.cd_pct_hh_income_45k_to_49k,
    cd_income.cd_hh_income_50k_to_59k,
    cd_income.cd_pct_hh_income_50k_to_59k,
    cd_income.cd_hh_income_60k_to_74k,
    cd_income.cd_pct_hh_income_60k_to_74k,
    cd_income.cd_hh_income_75k_to_99k,
    cd_income.cd_pct_hh_income_75k_to_99k,
    cd_income.cd_hh_income_100k_to_124k,
    cd_income.cd_pct_hh_income_100k_to_124k,
    cd_income.cd_hh_income_125k_to_149k,
    cd_income.cd_pct_hh_income_125k_to_149k,
    cd_income.cd_hh_income_150k_to_199k,
    cd_income.cd_pct_hh_income_150k_to_199k,
    cd_income.cd_hh_income_200k_or_more,
    cd_income.cd_pct_hh_income_200k_or_more,
    cd_income.cd_median_family_income,
    state_income.state_hh_income_total,
    state_income.state_pct_hh_income_total,
    state_income.state_hh_income_less_10k,
    state_income.state_pct_hh_income_less_10k,
    state_income.state_hh_income_10k_to_14k,
    state_income.state_pct_hh_income_10k_to_14k,
    state_income.state_hh_income_15k_to_19k,
    state_income.state_pct_hh_income_15k_to_19k,
    state_income.state_hh_income_20k_to_24k,
    state_income.state_pct_hh_income_20k_to_24k,
    state_income.state_hh_income_25k_to_29k,
    state_income.state_pct_hh_income_25k_to_29k,
    state_income.state_hh_income_30k_to_34k,
    state_income.state_pct_hh_income_30k_to_34k,
    state_income.state_hh_income_35k_to_39k,
    state_income.state_pct_hh_income_35k_to_39k,
    state_income.state_hh_income_40k_to_44k,
    state_income.state_pct_hh_income_40k_to_44k,
    state_income.state_hh_income_45k_to_49k,
    state_income.state_pct_hh_income_45k_to_49k,
    state_income.state_hh_income_50k_to_59k,
    state_income.state_pct_hh_income_50k_to_59k,
    state_income.state_hh_income_60k_to_74k,
    state_income.state_pct_hh_income_60k_to_74k,
    state_income.state_hh_income_75k_to_99k,
    state_income.state_pct_hh_income_75k_to_99k,
    state_income.state_hh_income_100k_to_124k,
    state_income.state_pct_hh_income_100k_to_124k,
    state_income.state_hh_income_125k_to_149k,
    state_income.state_pct_hh_income_125k_to_149k,
    state_income.state_hh_income_150k_to_199k,
    state_income.state_pct_hh_income_150k_to_199k,
    state_income.state_hh_income_200k_or_more,
    state_income.state_pct_hh_income_200k_or_more,
    state_income.state_median_family_income,
    us_income.us_hh_income_total,
    us_income.us_pct_hh_income_total,
    us_income.us_hh_income_less_10k,
    us_income.us_pct_hh_income_less_10k,
    us_income.us_hh_income_10k_to_14k,
    us_income.us_pct_hh_income_10k_to_14k,
    us_income.us_hh_income_15k_to_19k,
    us_income.us_pct_hh_income_15k_to_19k,
    us_income.us_hh_income_20k_to_24k,
    us_income.us_pct_hh_income_20k_to_24k,
    us_income.us_hh_income_25k_to_29k,
    us_income.us_pct_hh_income_25k_to_29k,
    us_income.us_hh_income_30k_to_34k,
    us_income.us_pct_hh_income_30k_to_34k,
    us_income.us_hh_income_35k_to_39k,
    us_income.us_pct_hh_income_35k_to_39k,
    us_income.us_hh_income_40k_to_44k,
    us_income.us_pct_hh_income_40k_to_44k,
    us_income.us_hh_income_45k_to_49k,
    us_income.us_pct_hh_income_45k_to_49k,
    us_income.us_hh_income_50k_to_59k,
    us_income.us_pct_hh_income_50k_to_59k,
    us_income.us_hh_income_60k_to_74k,
    us_income.us_pct_hh_income_60k_to_74k,
    us_income.us_hh_income_75k_to_99k,
    us_income.us_pct_hh_income_75k_to_99k,
    us_income.us_hh_income_100k_to_124k,
    us_income.us_pct_hh_income_100k_to_124k,
    us_income.us_hh_income_125k_to_149k,
    us_income.us_pct_hh_income_125k_to_149k,
    us_income.us_hh_income_150k_to_199k,
    us_income.us_pct_hh_income_150k_to_199k,
    us_income.us_hh_income_200k_or_more,
    us_income.us_pct_hh_income_200k_or_more,
    us_income.us_median_family_income
from cd_income
left join state_income
    on cd_income.state_fip = state_income.state_fip
        and cd_income.year = state_income.year
left join us_income
    on cd_income.country = us_income.country
        and cd_income.year = us_income.year
order by cd_income.state_fip, cd_income.congressional_district, cd_income.year
