name: Test DBT Workflow

on:
  workflow_dispatch:

jobs:
  test-auth:
    runs-on: ubuntu-latest
    permissions:
      contents: read   # Required to access the repository
      id-token: write  # Needed for Workload Identity Federation authentication

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}

      - name: Set up Cloud SDK and BigQuery CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          install_components: 'bq'

      - name: Set GCP Project
        run: |
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      - name: Run BigQuery test
        run: |
          gcloud auth list 
          bq ls
