
name: Test DBT Workflow

on:
  workflow_dispatch:

jobs:
  test-auth:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: '***REMOVED***'
          service_account: "***REMOVED***"
          create_credentials_file: true
          token_format: 'access_token'
          access_token_lifetime: '3600s'
          access_token_scopes: 'https://www.googleapis.com/auth/cloud-platform'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: 'votr-dev-430215'
          install_components: 'bq'

      - name: Authenticate gcloud
        run: |
          gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}"
          gcloud config set project votr-dev-430215

      - name: Run simple BigQuery test
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ steps.auth.outputs.credentials_file_path }}
        run: |
          gcloud auth list
          bq ls
# jobs:
#   test-auth:
#     runs-on: ubuntu-latest
#     permissions:
#       contents: read
#       id-token: write

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4

#       - id: 'auth'
#         name: 'Authenticate to Google Cloud'
#         uses: google-github-actions/auth@v2
#         with:
#           workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
#           service_account: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}


#       # - name: Test BigQuery Access
#       #   uses: google-github-actions/setup-gcloud@v2

#       - name: Set up Cloud SDK
#         uses: google-github-actions/setup-gcloud@v1
        
      # - name: Auth Info
      #   run: |
      #     echo "Using credentials from: ${{ steps.auth.outputs.credentials_file_path }}"
      #     gcloud auth list
      #     gcloud config list

      # - name: Configure BigQuery Auth
      #   run: |
      #     gcloud auth activate-service-account --key-file="${{ steps.auth.outputs.credentials_file_path }}"
      #     export GOOGLE_APPLICATION_CREDENTIALS="${{ steps.auth.outputs.credentials_file_path }}"
          
      # - name: Test BigQuery Access
      #   run: bq ls

# name: Test DBT Workflow

# # Allow manual trigger
# on:
#   workflow_dispatch:

# jobs:
#   test-auth:
#     runs-on: ubuntu-latest
#     permissions:
#       contents: read
#       id-token: write

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4

#       - name: Google Auth
#         id: auth
#         uses: google-github-actions/auth@v2
#         with:
#           workload_identity_provider: '***REMOVED***'
#           service_account: "***REMOVED***"

#       - name: Test BigQuery Access
#         uses: google-github-actions/setup-gcloud@v2

#       - name: Run simple BigQuery test
#         run: bq ls