name: Test DBT Workflow

# Allow manual trigger
on:
  workflow_dispatch:

jobs:
  test-auth:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: '***REMOVED***'
          service_account: "dbt-service-account@votr-dev-430215.iam.gserviceaccount.com"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: '>= 363.0.0'
          
      - name: Configure gcloud
        run: |
          gcloud config set project votr-dev-430215
          gcloud auth configure-docker

      - name: Test BigQuery Access
        run: |
          gcloud auth list
          bq ls