name: Run DBT

on:
  schedule:
    - cron: '0 5 * * *'  # Runs at 5 AM UTC daily
  workflow_dispatch:


jobs:
  test-auth:
    runs-on: ubuntu-latest
    permissions:
      contents: read   # Required to access the repository
      id-token: write  # Needed for Workload Identity Federation authentication

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
          create_credentials_file: true
          token_format: 'access_token'
          access_token_lifetime: '3600s'
          access_token_scopes: 'https://www.googleapis.com/auth/cloud-platform'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
            python-version: '3.9'
            cache: 'pip'

      - name: Set up Cloud SDK and BigQuery CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          install_components: 'bq'

      - name: Set GCP Project
        run: |
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}